**Что происходит, если функция нарушает спецификацию исключений?**  
Вызов обработчика unexpected
